version: "3.4"
services:
  minio:
    image: datashield/minio:ci
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    command: server /data
  armadillo:
    image: datashield/armadillo:ci
    environment:
      SPRING_PROFILES_ACTIVE: development
      MINIO_URL: http://minio
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
      RSERVE_HOST: rserver
      LOGGING_CONFIG: 'classpath:logback-file.xml'
      AUDIT_LOG_PATH: '/app/logs/audit.log'
      DATASHIELD_WHITELIST: dsBase,dsDanger,resourcer
    ports:
      - 8080:8080
  rserver:
    image: datashield/rserver:ci
    environment:
      DEBUG: "FALSE"
    ports:
      - 6311:6311
