version: "3.4"

services:
    armadillo:
        hostname: armadillo
        image: datashield/armadillo3:test
        environment:
            RSERVE_HOST: rserver
            DEBUG: "FALSE"
        ports:
            - 8080:8080
    rserver:
        hostname: rserver
        image: datashield/armadillo-rserver_caravan-yak:1.0.0
        environment:
            DEBUG: "FALSE"
        ports:
            - 6311:6311
