version: "3.4"

services:
    armadillo:
        hostname: armadillo
        ports:
            - 8080:8080
        build:
            context: '.'
            dockerfile: 'Dockerfile'
            args:
                JAR_FILE: '*.jar'
        image: datashield/armadillo_citest:2.0.0
        environment:
            LOGGING_CONFIG: 'classpath:logback-file.xml'
            AUDIT_LOG_PATH: '/app/logs/audit.log'
            SPRING_SECURITY_USER_PASSWORD: 'admin'
        volumes:
            - ${PWD}/tests/docker/armadillo/standard/logs:/logs
            - ${PWD}/tests/docker/armadillo/standard/data:/data
            - ${PWD}/tests/docker/armadillo/standard/config:/config
            - /var/run/docker.sock:/var/run/docker.sock

    default:
        hostname: default
        image: datashield/rock-dolomite-xenon:latest
        environment:
            DEBUG: "FALSE"
